import unittest
from pathlib import Path

try:
    from tests.createphase2fixtures import FIXTURES_DIR
    HAS_DOCX = True
except ImportError:
    HAS_DOCX = False
    FIXTURES_DIR = Path("tests/fixtures/generated")

import sys

class Phase2FixturesTests(unittest.TestCase):
    @unittest.skipIf(not HAS_DOCX, "python-docx not installed")
    @unittest.skipIf(sys.platform != 'win32', "COM not available on Linux")
    def test_fixtures_exist(self):
        # The fixtures should be generated by the script before this runs in the gate
        # If they don't exist, this fails, ensuring the generator works
        if FIXTURES_DIR.exists():
            self.assertTrue((FIXTURES_DIR / "Fixture_A_AutoFix.docx").exists() or not list(FIXTURES_DIR.glob("*.docx")))
