from __future__ import annotations


TOOL_COMMENT_AUTHOR = "MVA"
TOOL_COMMENT_INITIALS = "MVA"

COMMENT_MODE_APPEND = "append"
COMMENT_MODE_REPLACE = "replace"


def normalize_comment_mode(
    value: str,
) -> str:
    """Convert GUI/user text into an internal comment mode."""

    normalized = value.strip().casefold()

    if normalized in {
        "append",
        "append comments",
    }:
        return COMMENT_MODE_APPEND

    return COMMENT_MODE_REPLACE


def is_tool_comment_metadata(
    author: str,
    initials: str,
) -> bool:
    """
    Return True only for comments generated by this tool.

    Human comments remain untouched.
    """

    return (
        author.strip() == TOOL_COMMENT_AUTHOR
        and initials.strip() == TOOL_COMMENT_INITIALS
    )


def remove_prior_tool_comments(
    document,
) -> int:
    """
    Remove only prior comments generated by this tool.

    Word COM comments are deleted in reverse order to avoid invalidating
    the collection while iterating.
    """

    removed_count = 0

    for index in range(
        document.Comments.Count,
        0,
        -1,
    ):
        try:
            comment = document.Comments.Item(
                index
            )

            author = str(
                comment.Author or ""
            )

            initials = str(
                comment.Initial or ""
            )

            if not is_tool_comment_metadata(
                author,
                initials,
            ):
                continue

            comment.Delete()

            removed_count += 1

        except Exception as error:
            print(
                "Unable to inspect/remove prior comment "
                f"{index}: {error}"
            )

    return removed_count
